language: python
dist: xenial          #required for Python >= 3.7
python: '3.7'
sudo: required

install:
  - pip3 install -r requirements.txt

#command to run tests
script:
  - python app.py

after_Script: cd ~

deploy:
  provider: pages
  local_dir: /
  skip_cleanup: true
  github_token: xb7AQgPl5fJgTVfY_WawDw
  keep_history: true
  app: nasa-api
  repo: abrahym-sharfeldden/nasa-api
  on:
    branch: gh-pages